server {
    listen 80;
    server_name areteia.site www.areteia.site localhost;

    root /var/www/html;
    index index.php index.html index.htm;

    # The maximum allowed size of the client request body.
    client_max_body_size 100M;

    # Moodle slash arguments (essential for UI/CSS/JS)
    rewrite ^/(.*\.php)(/.*)$ /$1?file=$2 last;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Hide some Moodle files
    location ~ (/vendor/|/node_modules/|/composer.json|/composer.lock|/package.json|/package-lock.json) {
        deny all;
    }

    location ~ [^/]\.php(/|$) {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass moodle:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        # Essential for slash arguments
        fastcgi_param PATH_INFO $fastcgi_path_info;
        
        # Override headers to match the external port
        fastcgi_param HTTP_HOST localhost:8080;
        fastcgi_param SERVER_PORT 8080;

        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
    }


    location /dataroot/ {
        internal;
        alias /var/www/moodledata/;
    }

    # Better static file handling
    location ~ \.(css|js|jpg|jpeg|gif|png|ico|svg|woff|woff2|ttf|otf|mp3|mp4|ogg|wav|zip|gz|tar|tgz|bz2|7z|rar|pdf|doc|docx|xls|xlsx|ppt|pptx|txt|rtf|csv|xml|json)$ {
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    location ~ /\.ht {
        deny all;
    }
}
